### PR TITLE
Add development and deployment images

### PR DESCRIPTION
**Pull request by abhinavaggarwal**
Add docker images for dev and deploy workflows along with a helper script named run_job.sh to launch flexus simulator jobs on image checkpoints, inside a kubernetes cluster.

### CODE REVIEW

**Comment by Hnefi** [comment]
Looks good so far ahbinav. I have two requests:
1) Can you change run_job so it doesn't take a hardcoded version of qflex_dev:v6? Instead, the user should be able to pass the container name.
2) When you iterate over the checkpoints, can you add a quick explanation that these are the QEMU images to be run in trace-mode?

**Review by Hnefi — CHANGES_REQUESTED** [review]
Looks good so far ahbinav. I have two requests:

    Can you change run_job so it doesn't take a hardcoded version of qflex_dev:v6? Instead, the user should be able to pass the container name.
    When you iterate over the checkpoints, can you add a quick explanation that these are the QEMU images to be run in trace-mode?

**Comment by abhinavaggarwal** [comment]
Done.

**Comment by Hnefi** [comment]
👍

**Review by Hnefi — APPROVED** [review]

**Pull request merged**
